---
<% confset = { ipaddress: "zerohost", name: "127.0.0.1" } %>
settings:
  command_base: /usr/local/bundle/bin/knife

commands:
<% confset.each_pair do |target, node| %>
  - name: boot_<%= target %>
    command: zero bootstrap 127.0.0.1
    condition:
    options:
      node-name: <%= node %>
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
      overwrite:
      json-attribute-file: fixtures/sample.json
      bootstrap-version: latest
  - name: converge_<%= target %>
    command: zero converge
    condition: 'name:<%= node %>'
    options:
      attribute: knife_zero.host
      override-runlist: 'kzi::default'
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
  - name: converge2_<%= target %>
    command: zero converge --client-version latest
    condition: 'name:<%= node %>'
    options:
      attribute: knife_zero.host
      override-runlist: 'kzi::default'
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
  - name: converge3_<%= target %>
    command: zero converge
    condition: 'name:<%= node %>'
    options:
      attribute: knife_zero.host
      override-runlist: 'kzi::default'
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
      json-attribute: fixtures/sample2.json
<% end %>
  - name: boot_policy
    command: zero bootstrap 127.0.0.1
    condition:
    options:
      node-name: policy1
      policy-name: integration_test
      policy-group: local
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
      overwrite:
      bootstrap-version: latest
  - name: converge_policy
    command: zero converge
    condition: 'name:policy1'
    options:
      attribute: knife_zero.host
      named-run-list: replay
      ssh-user: docker
      connection-password: docker
      sudo:
      verbose:
