---
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Metrics/LineLength:
  Max: 180
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Max: 150
Style/RedundantSelf:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
